version: '3.8'

services:
  # Основной API (FastAPI)
  api:
    build: ./app
    container_name: crypto_api
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_HOST: timescaledb
    depends_on:
      - timescaledb
    restart: always

  # TA Worker (Фоновый расчет индикаторов)
  worker:
    build: ./app
    container_name: crypto_worker
    command: python3 worker.py
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_HOST: timescaledb
    depends_on:
      - timescaledb
    restart: always

  # Сервис загрузки данных
  collector:
    build: ./collector
    volumes:
      - ./data:/data
    restart: "no"

  # База данных
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: crypto_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ts_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always

volumes:
  ts_data: